apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: calico-kube-controllers-rolebinding
subjects:
- kind: ServiceAccount
  name: calico-kube-controllers
  namespace: kube-system
roleRef:
  kind: Role
  name: calico-kube-controllers-role
  apiGroup: rbac.authorization.k8s.io
