apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system
data:
  calico_backend: bird
  typha_service_name: "none"
  # Configure the Calico network settings.
  veth_mtu: "1440"
  ipip_enabled: "true"  # Ensure this is set to true
  vxlan_enabled: "false"