network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [10.0.2.40/8]
      routes:
        - to: 0.0.0.0/0
          via: 10.0.2.2
          on-link: true
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]